services:
  - type: web
    name: whats-app-bot
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"

    disk:
      name: wa-auth
      mountPath: /var/data
      sizeGB: 1
